import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* min-w-0 stops this flex item from refusing to shrink below a wide
            descendant's intrinsic width (e.g. a table) and blowing out the
            page with horizontal scroll — flex items default to min-width:auto. */}
        <div className="min-w-0 flex-1">{children}</div>
      </body>
    </html>
  );
}
